baseURL = "https://luscinia-newsite.netlify.app"
languageCode = "en-CA"
title = "Luscinia Enterprises"
theme = "hugo-fresh"
googleAnalytics = "UA-125101127-4"
disableKinds = [
  "taxonomy",
  "taxonomyTerm"
]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = false

[params]
openGraph = true
description = "Luscinia Enterprises Assn. is a BC Registered nonprofit under the Societies Act. Luscinia aims to provide enhanced access to education technologies"
section4 = false

  [params.navbarlogo]
  image = "logos/lea.svg"
  link = "/"

  [params.font]
  name = "Open Sans"
  sizes = [
    400.0,
    600.0
  ]

  [params.hero]
  title = "Luscinia Enterprises Association"
  subtitle = "Building education technology for the developing internet."
  buttontext = "Visit Aristotle"
  buttonlink = "https://aristotle.luscinia.ca"
  image = "illustrations/undraw_rtk.svg"
  clientlogos = [
    "microsoft",
    "google"
  ]

  [params.section1]
  title = "Our Mission"
  subtitle = "Luscinia is determined to provide high quality educational services to anybody that has the drive to learn. We provide students, parents and teachers the tools they need to succeed."

    [[params.section1.tiles]]
    title = "Create"
    icon = "undraw_create"
    text = "We create open-source education technologies."
    url = "https://github.com/luscinia-enterprises"
    buttonText = "Visit the Codebase"

    [[params.section1.tiles]]
    title = "Inform"
    icon = "undraw_inform"
    text = "We collect information and report to teachers."
    url = "https://aristotle.luscinia.ca/about-us"
    buttonText = "Learn about Aristotle"

    [[params.section1.tiles]]
    title = "Educate"
    icon = "undraw_educate"
    text = "We teach students based on our published findings."
    url = "https://aristotle.luscinia.ca/register"
    buttonText = "Register on Aristotle"

  [params.section2]
  title = "Vision"
  subtitle = "We have created the ideal pipeline for educational reinforcement algorithms."

    [[params.section2.features]]
    title = "Assess"
    text = "When a student logs in for the first time, a profile is generated including our proprietary learning styles assessment system. This generates a cross-curricular baseline of their individual learning style and helps the algorithm determine where to start their studies."
    icon = "laptop-globe"

    [[params.section2.features]]
    title = "Analyze"
    text = "Our library of resources are analysed and a fit is determined with students. Students will be served the best fitting resources within the teachers selection and their response is taken as feedback for both themselves and the resource."
    icon = "doc-sync"

    [[params.section2.features]]
    title = "Adjust & Improve"
    text = "As students complete resources, our algorithm determines their response and will dynamically adjust their profile in terms of learning style. The algorithm is then tuned to ensure that students are always served the most relevant resources. This allows us to give feedback to teachers and parents on general performance."
    icon = "mobile-feed" 

  [params.section3]
  title = "Aristotle Education Platform"
  subtitle = "Cutting edge educational technologies for the developing internet."
  image = "illustrations/mockups/aristotle-mockup.png"
  buttonText = "Visit the Alpha"
  buttonLink = "https://aristotle.luscinia.ca"
	
  [params.footer]
  logo = "lea.svg"
  socialmediatitle = "Follow Us"
  bulmalogo = false

    [[params.footer.socialmedia]]
    link = "https://github.com/luscinia-enterprises/"
    icon = "github"

    [[params.footer.socialmedia]]
    link = "https://www.linkedin.com/company/luscinia-enterprises"
    icon = "linkedin"

  [[params.navbar]]
  title = "Our Team"
  url = "/our-team/"

  [[params.navbar]]
  title = "Careers"
  url = "/careers/"
  
  [[params.navbar]]
  title = "Aristotle"
  url = "https://aristotle.luscinia.ca"

  [[params.navbar]]
  title = "Plato"
  url = "https://platolearning.ca"

  [[params.navbar]]
  title = "Sponsor Us"

    [[params.navbar.sublinks]]
    title = "GitHub Sponsors"
    url = "https://github.com/sponsors/luscinia-enterprises"

    [[params.navbar.sublinks]]
    title = "Donate"
    url = "https://luscinia-donate.square.site/"

    [[params.navbar.sublinks]]
    title = "Corporate Donations"
    url = "mailto:finance@luscinia.ca"
